name: trove

services:
  # GraphQL API
  backend:
    image: "${DOCKER_USER:-acetankace}/trove_backend:${VERSION:-latest}"
    container_name: trove_backend
    restart: unless-stopped
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  # React + Nginx
  frontend:
    image: "${DOCKER_USER:-acetankace}/trove_frontend:${VERSION:-latest}"
    container_name: trove_frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8080:80"