name: trove

services:
  # GraphQL API
  backend:
    image: "${DOCKER_USER:-acetankace}/trove_backend:${VERSION:-latest}"
    container_name: trove_backend
    restart: unless-stopped
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  # React + Nginx
  frontend:
    image: "${DOCKER_USER:-acetankace}/trove_frontend:${VERSION:-latest}"
    container_name: trove_frontend
    depends_on:
      - backend
    restart: unless-stopped
    expose:
      - "80"

  caddy:
    image: caddy:2
    container_name: trove_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - caddy_data:/data        # certs
      - caddy_config:/config
    depends_on:
      - frontend

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    restart: unless-stopped
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: host.docker.internal
      KC_DB_URL_PORT: ${POSTGRES_PORT}
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"

volumes:
  caddy_data:
  caddy_config:
  keycloak_data:

networks:
  trove_net:
    driver: bridge